# Generated by Django 3.1.1 on 2020-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(default='na', upload_to='pics'),
            preserve_default=False,
        ),
    ]
