# Generated by Django 3.1.1 on 2020-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_products_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Clothe_Type',
            field=models.CharField(choices=[('SA', 'Saree'), ('KU', 'Kurta'), ('DU', 'Dupatha')], default='SA', max_length=100),
        ),
    ]
