# Generated by Django 3.1.1 on 2020-10-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_products_clothe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Clothe_Type',
            field=models.CharField(choices=[('Saree', 'Saree'), ('Kurta', 'Kurta'), ('Dupatha', 'Dupatha')], default='Saree', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='Material',
            field=models.CharField(choices=[('Silk', 'Silk'), ('Cotton', 'Cotton')], default='Cotton', max_length=100),
        ),
    ]
