# Generated by Django 3.1.1 on 2020-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20201002_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Clothe_Type',
            field=models.CharField(choices=[('SA', 'Saree'), ('KU', 'Kurta'), ('DU', 'Dupatha')], default='SA', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='Material',
            field=models.CharField(choices=[('S', 'Silk'), ('C', 'Cotton')], default='C', max_length=100),
        ),
    ]
