# Generated by Django 3.1.1 on 2020-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_auto_20201003_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.CharField(choices=[('CKS', 'Chanderi Kataan Silk'), ('CSK', 'Chanderi Silk Cotton'), ('CSS', 'Chanderi Soft Silk'), ('KaSC', 'Kanchipuram Silk Cotton'), ('KuSC', 'Kuppadam Silk Cotton'), ('LC', 'Linen Cotton'), ('SL', 'Silk Linen')], default='CKS', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='Vendor',
            field=models.CharField(choices=[('KS', 'KS'), ('RM', 'RM'), ('AP', 'AP')], default='KS', max_length=100),
        ),
    ]
